### ISSUE TITLE
Create todo model

### ISSUE THREAD

**Issue by MoigeMatino** [MoigeMatino/fastapi-htmx-todo#15]
Create todo model in db and use SQLModel as ORM and for validation through pydantic.

- [x] create `models.py` and create todo model
- [x] create settings configs
- [x] create `.env` file to save environment variables
- [x] create `database.py`
